### ISSUE TITLE
step1  리뷰

### ISSUE THREAD

**Issue by soleJin** [hakju/ios-cloud-notes#23]
1. ~~ListCell-require init & fetal error~~
2. ~~Memo-dateToString~~
3. ~~MainView-splitViewController:[setViewController(_ vc: UIViewController?, for column: UISplitViewController.Column)](url)~~
4. ~~MainView-splitViewController: size에 맞게 DoubleColumn 보여주는 방법 [https://developer.apple.com/documentation/uikit/uisplitviewcontrollerdelegate](url)~~
5. ~~DetailViewController-line90: guard와 if의 차이~~
6. ~~DetailViewController-line113-116: NSRange.int / NSMakeRange 차이~~
7. ~~DetailViewController-line111-113: position/Range~~

**Comment by hakju** [comment]
쏠 3, 6
꼬말 4, 7

**Comment by hakju** [comment]
완료~ (찡긋)

**Comment by soleJin** [comment]
> 완료~ (찡긋)

우와 :) 찡긋ㅋㅋㅋㅋㅋㅋㅋ
